- packages/tinybased/src/fixture/database.ts
- packages/tinybased/src/lib/queries/SimpleQuery.ts
- packages/tinybased/src/lib/tinybased-react.spec.ts
- packages/tinybased/src/lib/tinybased-react.ts
- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- packages/tinybased/src/lib/types.ts
- Adds ability to sort a SimpleQuery based on its selected fields.
- Works for queries that are manually invoked as well as reactively with hooks
- Implements `deleteCell`
> feat: adds support for sorted query results

- packages/tinybased/src/fixture/database.ts
- packages/tinybased/src/index.ts
- packages/tinybased/src/lib/SchemaBuilder.ts
- packages/tinybased/src/lib/TableBuilder.ts
- packages/tinybased/src/lib/queries/SimpleQuery.ts
- packages/tinybased/src/lib/queries/SimpleQueryBuilder.ts
- packages/tinybased/src/lib/tinybased-react.ts
- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- packages/tinybased/src/lib/types.spec.ts
- packages/tinybased/src/lib/types.ts
- Adds a new API for defining Tables using a fluent builder pattern. This allows us to infer types nicely while storing useful runtime metadata about table definitions. It also sets us up to be able to map nicely to the `setSchema` methods that are exposed by TinyBase itself
- Introduces the ability to define composite keys for entities which will be honored during hydration
- Adds the ability to represent potentially undefined cell values in our Table definitions
- Improves some types by making sure that we narrow keys down to only `string` and remove `number | Symbol` which means we don't have to cast to `as string` nearly as often
> feat: new table builder API

- packages/tinybased/.eslintrc.json
- packages/tinybased/src/lib/SchemaBuilder.ts
- packages/tinybased/src/lib/TableBuilder.ts
- packages/tinybased/src/lib/queries/SimpleQuery.ts
- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- packages/tinybased/src/lib/types.ts
Defines a new API which makes it easier to attach a Persistor to the SchemaBuilder. The purpose of the persistor is two fold: 
- A conveient way to ensure that data coming into a TinyBased instance are hydrated from external storage
- Ensures that all future changes to the TinyBased instance are automaticaly synced back to the external storage
This new API will make it much easier to define pluggable wrappers for syncing two and from things storage like IndexedDB, SQLite, a networked service, etc
> feat: adds APIs for definining persistors (hydrate + save) [CR-2567]

- packages/tinybased/src/lib/queries/SimpleQueryBuilder.ts
- packages/tinybased/src/lib/tinybased.spec.ts
Prevents the user from attempting to aggregate on a cell which hadn't been selected as part of the query. Doing so would result in the aggregation always returning undefined
> fix: only allow aggregation on selected cells [CR-2580]

- packages/tinybased/src/fixture/database.ts
- packages/tinybased/src/lib/tinybased-react.spec.ts
- packages/tinybased/src/lib/tinybased-react.ts
- packages/tinybased/src/lib/types.ts
* Exposes type-safe Relationship hooks and useRowIds hook
`type TinyBasedReactHooks<T>` Expects Tinybased build instance as generic instead of Tinybased Table schema, In able infer relationship names for relationship hooks.
> feat: Exposes type-safe Relationship hooks and useRowIds hook

- packages/tinybased/src/lib/tinybased-proofs.spec.ts
- packages/tinybased/src/lib/tinybased.spec.ts
- Included some tests that verify our assumptions when it comes to how undefined values interact with TinyBase and listeners
- This proves that setting a cell to undefined works as expected and also triggers listeners. **However**, it is important to note that the cell is actually removed from the row as opposed to having its value be set to undefined
> feat: add tests for verifying our assumptions about certain TinyBase functionality 

- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- Users can now update a bunch of cells for an existing row using a convenient syntax
- Improved types so that we don't have to do many `as string` casts
> feat: add method to simplify merging row data

- packages/tinybased/src/lib/SchemaBuilder.ts
- packages/tinybased/src/lib/types.ts
- Makes the onInit method of a persistor optional, since not all persistors will care about it
- Cleans up some more `any` to reduce lint warnings
> feat: make onInit optional for persistors

- packages/tinybased/src/lib/search/Searcher-react.spec.tsx
- packages/tinybased/src/lib/search/connectTinybasedSearcher.tsx
Older TS has issues getting the deep ReturnType of the `connectTinybasedSearcher`. This PR exposes a `UseSearchType` that dramatically simplifies declaring `useSearch` at the consumer level.
```typescript
// BEFORE
let builtSearch!: Awaited<
ReturnType<typeof connectTinybasedSearcher<Schema, 'users' | 'notes'>>
>;
let useSearch!: (typeof builtSearch)['useSearch'];
// NOW
let useSearch!: UseSearchType<Schema, 'users' | 'notes'>;
```
> feat(full text search): Improve the export type for useSearch

- packages/tinybased/src/lib/search/connectTinybasedSearcher.tsx
I had missed the explicit return type in the `connectTinybasedSearcher` method to use the new `UseSearchType`. This should ensure that it is accurately used for determining the type of `useSearch` when returned from `connectTinybasedSearcher`.
> fix(full text search): ensures that the return type of the connectTinybasedSearcher uses the new UseSearchType

- packages/tinybased/src/lib/queries/SimpleQuery.ts
- packages/tinybased/src/lib/tinybased-react.spec.ts
- packages/tinybased/src/lib/tinybased-react.ts
- packages/tinybased/src/lib/types.ts
- Adds another typesafe hook that allows all the rows of a table to sorted/paginated
> feat(hooks): typesafe useSortedRowIds for tables

- packages/tinybased/src/lib/tinybased-react.spec.ts
- packages/tinybased/src/lib/tinybased-react.ts
Ensures that when consuming results of aggreation queries in reacts that the types are properly inferred
> fix: types for useQueryResult for aggregate queries

- packages/tinybased/src/lib/SchemaBuilder.spec.ts
- packages/tinybased/src/lib/SchemaBuilder.ts
- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/types.ts
Fixes a tricky bug where it is tempting to re-use a schema builder as a template for spawning databases. However, this had the side effect of stacking persistors internal to the SchemaBuilder instance which could cause unwanted hydration of the previous DB's data
> fix: stacking persistors when re-using schema builder

- packages/tinybased/src/lib/TableBuilder.ts
- packages/tinybased/src/lib/search/connectTinybasedSearcher.tsx
- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- packages/tinybased/src/lib/types.ts
- Adds a new typesafe API for registering event listeners that are attached to row changes for a given table
- Does work to determine if this is an insert, update or delete event and give more contextual information back to the event handler to reduce boilerplate
> feat: add API for registering typesafe row change listeners [CR-2716]

- packages/tinybased/src/lib/queries/QueryBuilder.ts
We were running into some weird issues with `useQuery*` hooks where the query definition would be overwritten during mount/unmount using the same logical query body but it could cause unwanted re-renders
> fix: check if query exists before attempting to setDefintion again

- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- packages/tinybased/src/lib/types.ts
- Always include rowId in the payload
- For `update`, generate a changes object that only includes the keys that actually changed
- For `delete`, also pass back the last value of the row before the delete happened
> feat: improvements to onRowChange API [CR-2765]

- packages/tinybased/src/lib/SchemaBuilder.ts
- packages/tinybased/src/lib/TableBuilder.ts
- packages/tinybased/src/lib/queries/QueryBuilder.ts
Reverting prettify types due to typescript erroring `instantiation is excessively deep and possibly infinite`.
> fix: revert prettify types due to

- packages/tinybased/src/lib/tinybased-react.ts
We've been seeing strange behavior where queries that are leveraging these hooks get removed and then never put back. As a future optimization it would be nice to bring this functionality back but we need to identity some test suite that reproduces the issue so that we can verify that its been properly addressed
> fix: disable automatic query definition cleanup

- packages/tinybased/src/fixture/database.ts
- packages/tinybased/src/lib/SchemaBuilder.ts
- packages/tinybased/src/lib/TableBuilder.ts
- packages/tinybased/src/lib/search/searcher.spec.ts
- packages/tinybased/src/lib/search/tinybased-searcher.spec.ts
- packages/tinybased/src/lib/tinybased-react.spec.ts
- packages/tinybased/src/lib/tinybased-react.ts
- packages/tinybased/src/lib/tinybased.spec.ts
- packages/tinybased/src/lib/tinybased.ts
- Adds computed column support to tables
- `TableBuilder` has new `addComputed` method to allow a user to define a column that is computed based on the other columns in that row.
- `TinyBased`
- hydrators expect the computed column to be populated during hydration. The row listeners will not fire for the initial hydration.
- all getters types include the computed cells (`getRow`, `getTable`, `getCell`, `useRow`, `useCell`, etc.)
- all setters types exclude the computed cells (`setTable`, `setRow`, `setCell`), the consumer should never be directly setting computed cells
- Inter-table computed column support (possibly follow-up ticket) [CR-2993]
> Computed column support [CR-2758]

- packages/tinybased/src/lib/types.ts
The generic for the computed keys was missing from the `InferTinybasedFromSchemaBuilder`. This PR adds it so that they can be correctly used.
> fix(computed columns): updates InferTinybasedFromSchemaBuilder to account for computed columns[CR-3159]
